### ISSUE TITLE
Missing image in User Guide

### ISSUE THREAD

**Issue by xnickmx** [GoogleCloudPlatform/appengine-pipelines#10]
The "ComplexJob" child graph image is missing. When I attempt to load the image URL directly, it returns an HTTP 404 not found.

This is the user guide page URL: https://github.com/GoogleCloudPlatform/appengine-pipelines/wiki/Java

This is the missing image URL: https://camo.githubusercontent.com/1890ec0c618ae97fa60048f8f5cc3276fba29b25/68747470733a2f2f617070656e67696e652d706970656c696e652e676f6f676c65636f64652e636f6d2f73766e2f696d616765732f636f6d706c65786a6f622e706e67

**Comment by tkaitchuck** [comment]
I've added all of the missing images.
