### ISSUE TITLE
Remove usage of deprecated Files API

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/appengine-pipelines#18]
The API was deprecated in May 2013: https://cloud.google.com/appengine/docs/python/googlestorage/

The Pipeline API should be updated to use the cloudstorage library and the default GCS bucket (or configurable by user)

**Comment by burnhamup** [comment]
I've heard a rumor from Google that the Files API will be removed on May 1, 2015. This could render this library inoperable if this isn't fixed.

**Comment by tkaitchuck** [comment]
The only use is here:
https://github.com/GoogleCloudPlatform/appengine-pipelines/blob/master/python/src/pipeline/pipeline.py#L1222

This one function should be very easy to re-write. To use https://github.com/GoogleCloudPlatform/appengine-gcs-client

I am keeping this open so it is not forgotten.

**Comment by svpino** [comment]
I'll take a stab at this one. The only issue is that tests are not running right now. I already submitted a PullRequest #28 to fix them. I'll work on this locally and submit another PullRequest when ready.

**Comment by mattjo** [comment]
Here's a shot at removing the dependency. https://github.com/GoogleCloudPlatform/appengine-pipelines/pull/35

**Comment by mattjo** [comment]
https://github.com/GoogleCloudPlatform/appengine-pipelines/pull/37 was merged yesterday, so I think this issue is resolved.
