### ISSUE TITLE
Noisy logging.error: "Bad state for purpose"

### ISSUE THREAD

**Issue by soundofjw** [GoogleCloudPlatform/appengine-pipelines#50]
When debugging aborted pipelines, we tend to look to error logs with `path:pipeline` on the console.

In this search, you will find errors like the following:
`Pipeline ID "23377674aae54a8b883cb75636a8fcf6" in bad state for purpose "abort": "aborted"`

This specific message seems to me to be a bit verbose, as I'd expect this to be an okay situation.

----

There are perhaps 2 points of discussion worth having here:

1. The obvious, why is an aborted pipeline being triggered for abortion?
2. The more helpful, can we disable this particular log from emitting?

----

If the community finds it appropriate, I've tackled item 2 in #51 and its ready to be merged. 
If not, we can keep the change to our fork at github.com/Loudr/appengine-pipelines . :beers:

**Comment by tkaitchuck** [comment]
1 is inevitable. (Duplication / inconsistency / errors)
2. Sounds good.
