### ISSUE TITLE
Files API Still Being Used in the demo app

### ISSUE THREAD

**Issue by rbruyere** [GoogleCloudPlatform/appengine-pipelines#53]
Salutations,

The '_write_json_blob'[1] still uses the Files API that has been deprecated.

[1] https://github.com/GoogleCloudPlatform/appengine-pipelines/blob/824b1388f8e30d83f0eafeeb7b08243f9f1974ff/python/demo/pipeline/pipeline.py#L1222

**Comment by soundofjw** [comment]
You are looking at the source pointing to the demo app.

Compare with the same function on master in src:
https://github.com/GoogleCloudPlatform/appengine-pipelines/blob/master/python/src/pipeline/pipeline.py#L1241-L1277

This makes me wonder - why is the source duplicated in the demo app?

**Comment by tkaitchuck** [comment]
Fixed in 95bcc505aa2c16a3d9629a5e6400481503926c01
