### ISSUE TITLE
TaskQueue behavior for duplicate tasks in a list during Queue.add()

### ISSUE THREAD

**Issue by soundofjw** [GoogleCloudPlatform/appengine-pipelines#55]
I have some questions about the behavior of `taskqueue.Queue().add(task_list)` when 1 of the tasks is duplicate, but the others are not.

I am not aware of any documentation around the taskqueue API that explains this behavior - as such it seems undefined.

My concern is that adding a list of multiple tasks, where 1 may already have been tombstoned/created, may cause the other legitimate tasks to fail.

This affects the pipeline library in the following codeblock:

```python
try:
  taskqueue.Queue(self.queue_name).add(task_list)
except (taskqueue.TombstonedTaskError, taskqueue.TaskAlreadyExistsError):
  pass
```
> https://github.com/GoogleCloudPlatform/appengine-pipelines/blob/bd9fa1e7000dc6af6fe704137cc53fa6d8cde427/python/src/pipeline/pipeline.py#L1659-L1663

Any clues? This may be a good question for @tkaitchuck.
This was brought up in issue #54.

**Comment by tkaitchuck** [comment]
As far as I can tell this is ok. If it turns out not to be, it should be treated as a bug in taskqueue, as a TaskAlreadyExistsError should be raised at a lower priority than a failure for other reasons.

**Comment by soundofjw** [comment]
@tkaitchuck It's definitely a task-queue related question, but it's unclear as to what happens to all 10 tasks when 1 out of 10 tasks is a duplicate. Any ideas?

**Comment by tkaitchuck** [comment]
I know that is the case for Java's task queue that all 10 will be attempted and only if there is no more serious error will that be raised. So I assume it is for the python client as well.
