### ISSUE TITLE
Target param ignored during retry attempts and barrier notifications.

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/appengine-pipelines#60]
Commit 443e3112b7f532ae70537c625c48e8b04cb326b1 addressed this previously, but it was reversed. I'll put in a PR shortly that tries it a different way.

**Comment by sit** [comment]
Can someone test/merge this?

@AngryBrock @tkaitchuck

**Comment by tkaitchuck** [comment]
This looks like it is fixed here:
https://github.com/GoogleCloudPlatform/appengine-pipelines/pull/61
@AngryBrock Any objections to merging?

**Comment by AngryBrock** [comment]
@tkaitchuck no objections from me.

**Comment by tkaitchuck** [comment]
Merged
