### ISSUE TITLE
waitFor doesn't support FutureList

### ISSUE THREAD

**Issue by gzussa** [GoogleCloudPlatform/appengine-pipelines#63]
If you create a job waiting on a list of other jobs, then it will throw an exception.
Example: futureCall(new myJob(), waitFor(futureList(previousJobsFutureValues))).
Here is the message I get in the UI:
com.google.appengine.tools.pipeline.FutureList cannot be cast to com.google.appengine.tools.pipeline.impl.FutureValueImpl

At a first and very quick glance, i think the issue is located in JobRecord#applySetting function at the following line of code:
FutureValueImpl<?> fv = (FutureValueImpl<?>) wf.getValue();

**Comment by aozarov** [comment]
Yes, you are correct. 

Current workaround is to create an array of `JobSetting.WaitForSetting` and pass the array as the `JobSetting` varargs value for `futureCall`.

**Comment by gzussa** [comment]
This is a better workaround than the one i did.
It consisted of creating a job with a dummy parameter of List<FutureValue<Void>>.
Example: futureCall(new myJob(previousJobsFutureValues))
