### ISSUE TITLE
Pipelines requires different version of simplejson than mapreduce

### ISSUE THREAD

**Issue by ksookocheff-va** [GoogleCloudPlatform/appengine-pipelines#9]
The simplejson lib should be added as a separate dependency (like what was done with the MapReduce library). The versions of these libs should be the same.

**Comment by someone1** [comment]
Is there a reason why it isn't:

```python
try:
  import json as simplejson
except:
  import simplejson
```

?

For those of us that use the python27 runtime, we can benefit from the speedups afforded by the stdlib json import that has compiled c speedups and remove a dependency.

**Comment by tkaitchuck** [comment]
Someone1: Good Point. Can you send a merge request?
Is there any other reason to keep this open?
